### ISSUE TITLE
mistake on annotation

### ISSUE THREAD

**Issue by jihobak** [naturomics/CapsNet-Tensorflow#13]
I think there are some mistake on annotation. I found two.

[L61](https://github.com/naturomics/CapsNet-Tensorflow/blob/master/capsLayer.py#L61)
`
Reshape the input into [batch_size, 1, 1152, 8, 1]
--->

Reshape the input into [batch_size, 1152, 1, 8, 1]
`

[L77](https://github.com/naturomics/CapsNet-Tensorflow/blob/master/capsLayer.py#L77)
`
input: A Tensor with [batch_size, 1, num_caps_l=1152, length(u_i)=8, 1]
--->

input: A Tensor with [batch_size, num_caps_l=1152, 1, length(u_i)=8, 1]
`

order should be change I think

Thanks

**Comment by naturomics** [comment]
merged
