### ISSUE TITLE
Why num_outputs is mandatory?

### ISSUE THREAD

**Issue by thibo73800** [naturomics/CapsNet-Tensorflow#15]
https://github.com/naturomics/CapsNet-Tensorflow/blob/1e0668037447e89aca9173a688ce1965bf6a43c1/capsNet.py#L45

Why `num_outputs` is set in this while it will not be used?

**Comment by naturomics** [comment]
@thibo73800 the 'num_outputs' para should be used in [this line](https://github.com/naturomics/CapsNet-Tensorflow/blob/1e0668037447e89aca9173a688ce1965bf6a43c1/capsLayer.py#L66): b_IJ = tf.zeros(shape=[1, 1152, 10, 1, 1], dtype=np.float32) => b_IJ = tf.zeros(shape=[1, 1152, num_outputs, 1, 1], dtype=np.float32), which is designed for extensibility. Of course, the '1152' can also be automatically calculated (I would like to replace all of number with parameters, making the code can be reused in more scenarios)

**Comment by thibo73800** [comment]
I can work on it if you want? With a pull request today or tomorrow morning?

**Comment by thibo73800** [comment]
Ok, but the meaning of num_outputs is in fact, the number of capsules in the "Fc" CapsulesLayer?

Thank you for your answer.

**Comment by naturomics** [comment]
@thibo73800 Yes, it is.
