### ISSUE TITLE
Comment is different from your code

### ISSUE THREAD

**Issue by tonysy** [naturomics/CapsNet-Tensorflow#18]
Hi, I think this two lines may be conflict, the shape of b is not as the comments
[shape confusing](https://github.com/naturomics/CapsNet-Tensorflow/blob/7832e63e34f3c825ebfba7aff5e3e7dc445753e8/capsLayer.py#L68-L69)

And for here,[line](https://github.com/naturomics/CapsNet-Tensorflow/blob/7832e63e34f3c825ebfba7aff5e3e7dc445753e8/capsLayer.py#L111-L114).
It was confusing also.

Please check it.

**Comment by naturomics** [comment]
Thanks for your commented
