### ISSUE TITLE
Training on different input dimensions than MNIST

### ISSUE THREAD

**Issue by servetcoskun** [naturomics/CapsNet-Tensorflow#19]
Thanks for writing the code so shortly after the article was released. I'm trying to change the structure such that the capsule network can be trained for any image(x,y,z), but I am having trouble re-structuring the code. Can you help me identify which lines needs to be modified. I am guessing all lines with ... 28, 28, 1) -> ... 32, 32, 3) for CIFAR 10. But I am still not able to make it work.

Thank you again 👍

**Comment by naturomics** [comment]
@servetcoskun I'm going to release a new version which is dimensional compatible for different image size in these two days. Maybe you can wait for a few days, I'm trying my best to make this code to be more reusable and easier to use.

Thanks for your follow

**Comment by servetcoskun** [comment]
Is it possible to get an update :)? Good work on the commits 👍

**Comment by utkarshcontractor** [comment]
Thanks for sharing the implementation @naturomics ! dimensional compatible for different image sizes would be very useful to adapt caps net to different use cases. Thanks in advance

**Comment by djoffrey** [comment]
Has any update to this issue commited?

**Comment by naturomics** [comment]
I've created a new project [CapsLayer](https://github.com/naturomics/CapsLayer), which should be able to meet the dimensional compatible requirement. Please see the details in [the project homepage](https://github.com/naturomics/CapsLayer).
