### ISSUE TITLE
Is your b_ij wrong?

### ISSUE THREAD

**Issue by junfanlin** [naturomics/CapsNet-Tensorflow#2]
Hi,
  Thanks for your contribution. And I think the b_ij defined in your code probably is unmatched with the paper. 
Your code is:
```
self.b_ij = tf.get_variable('b_ij', shape=(1, 1152, 1, 1))
...
c_i = tf.nn.softmax(self.b_ij, dim=1)
```

But in fact it should be
```
b_i = tf.get_variable(‘b_i’, shape=(1, 1152, 16, 1))
...
c_i = tf.nn.softmax(b_i, dim=2)
```

If I have misunderstand your code, please ignore me. Thanks~

**Comment by naturomics** [comment]
@junfanlin Indeed, there are some problems including the one you found, I'm fixing it, thanks for your reminding.

**Comment by naturomics** [comment]
@junfanlin I read the paper several times again, I think you misunderstood the c_ij and b_ij. They are all scalar value, as the paper behind Eq.2 says:

> where  the c_ij are coupling coefficients that are determined by the iterative dynamic routing process.
> The coupling coefficients between capsule i and all the capsules in the layer above sum to 1 (scalar) and ...
