### ISSUE TITLE
Try Fashion-MNIST

### ISSUE THREAD

**Issue by hanxiao** [naturomics/CapsNet-Tensorflow#20]
Could you please test and post the result on Fashion-MNIST? https://github.com/zalandoresearch/fashion-mnist

It shares the same size & format as mnist, should be straightforward to integrate.

**Comment by servetcoskun** [comment]
I will try running CapsNet on Fashion-MNIST this weekend 👍

**Comment by changkun** [comment]
I did it for Fashion MNIST few times, max acc only 92% (8M params, 50 epochs), whereas I can do a better performance about 95% with plain CNN (1M params, 10 epochs), quite disappointing actually.
