### ISSUE TITLE
Set batch = 1 error

### ISSUE THREAD

**Issue by MilesZhao** [naturomics/CapsNet-Tensorflow#22]
When I set batch as 1, there is a value error when building the graph. I think it was caused the [this line ](https://github.com/naturomics/CapsNet-Tensorflow/blob/master/capsNet.py#L88)of code.

**Comment by naturomics** [comment]
This is due to the using of the `tf.squeeze ` in this line:
>self.masked_v = tf.matmul(tf.squeeze(self.caps2), tf.reshape(self.Y, (batch_size, 10, 1)), transpose_a=True)

But, who will set batch size to 1 ?
