### ISSUE TITLE
Note to Huadong

### ISSUE THREAD

**Issue by TarrySingh** [naturomics/CapsNet-Tensorflow#28]
Hi Huadong,

I've been running succesful tests of CapsNets with Pytorch and would like to compare notes with you. Maybe we can take our discussion offline?
My email is: firstname.lastname[@]gmail.com

Let me know!

Tarry

**Comment by naturomics** [comment]
@TarrySingh I'v sent you an email,please check it

**Comment by TarrySingh** [comment]
Got it!
