### ISSUE TITLE
Should we squash in the PrimaryCaps layer?

### ISSUE THREAD

**Issue by junfanlin** [naturomics/CapsNet-Tensorflow#3]
Hi,
  Sorry to interrupt you again. I feel exicting when I see your work proceeding. I here realize that you do squashing operation in PrimaryCaps layer, which I don't see the reason. The paper uses squashing during routing process, but there is no routing process between Conv1 and PrimaryCaps. So I wonder is it reasonable to put squashing operation in PrimaryCaps layer? Expecting your reply! Thanks in advance.

**Comment by naturomics** [comment]
@junfanlin 
Yesterday I've pointed out this question at [知乎](https://zhihu.com/question/67287444/answer/251460831).
At the 3rd paragraph of Sec 4, it says:

>  One can see PrimaryCapsules as a Convolution layer with **Eq. 1 as its block non-linearity**

I'm sure the PrimaryCaps layer is squashed. But my question is: dose the paper do non-linearity activation like ReLU in the PrimaryCaps layer([this line](https://github.com/naturomics/CapsNet-Tensorflow/blob/6a11bbde8d9de162e5c95bec1b00ee211d59c9bb/capsLayer.py#L36)) at the same time? I don't know, but we can simply modify this tow line: [code 1](https://github.com/naturomics/CapsNet-Tensorflow/blob/6a11bbde8d9de162e5c95bec1b00ee211d59c9bb/capsLayer.py#L36) and  [code 2](https://github.com/naturomics/CapsNet-Tensorflow/blob/6a11bbde8d9de162e5c95bec1b00ee211d59c9bb/capsLayer.py#L48) to do an experiment to see which is better. I will note this question in the code. Thank you.

**Comment by junfanlin** [comment]
Thank you very much! I think I missunderstood this part, but now it's corrected. Thanks again!
