### ISSUE TITLE
If this version has no test or predict function.

### ISSUE THREAD

**Issue by shijh1975** [naturomics/CapsNet-Tensorflow#31]
Hello, I want to test the data I generate myself, But I can not see how can I do?

**Comment by naturomics** [comment]
It has, just for test accuracy now. The code is [here](https://github.com/naturomics/CapsNet-Tensorflow/blob/2f8cf8bbab6b1d61d254932e16a7061ee08bc70d/main.py#L46) and [here](https://github.com/naturomics/CapsNet-Tensorflow/blob/2f8cf8bbab6b1d61d254932e16a7061ee08bc70d/capsNet.py#L154). But this version is not designed for other datasets yet. If you want to test it with your data, maybe you should change some code(change the dimension of variables to suit your data). I'm too busy these days, I'll do my best to release a new version with better compatibility ASAP.

**Comment by shijh1975** [comment]
thks！I will change zhe code for predict!
