### ISSUE TITLE
[Question] Could the CapsNet unit apply to other more complex architecture ?

### ISSUE THREAD

**Issue by rild** [naturomics/CapsNet-Tensorflow#34]
Hi! 

I'm a student interested in Speech Synthesis with neural networks.
I suppose this CapsNet might improve the quality of synthesized speech, 
so I try to apply this great program to the other program to generate artificial speech with neural network.
 
I would like to ask whether this CapsNet could replace other popular neural networks like CNN.

Thank you for answering.

**Comment by naturomics** [comment]
@rild I'm not sure about that. I think capsule as a new concept that is equivalent to the concept of neuron but does the calculation in the way of vector in and vector out. It's a potential thing which will promote great development of deep learning. In conclusion, the concept of capsule is general, and capsNet might work in speech synthesis, just try it——Even if it doesn't work today, it will work tomorrow :smile_cat:

**Comment by rild** [comment]
@naturomics Thank you!

I'm relieved to hear that capsule does the calculation in the way of vector i/o, and has a possibility of applications. 

I was anxious because I could not get how to implement the CapsNet to other architecture.

> Even if it doesn't work today, it will work tomorrow

That is exactly right.
I'll try various things with CapsNet.

Thank you for prompt response.

**Comment by WhiteFu** [comment]
Have you tried to use the capsNet to replace the CNN in the speech synthesis network? Does it work well?
