### ISSUE TITLE
Run in GTX960M get error [InternalError (see above for traceback): Dst tensor is not initialized.]——out of memory

### ISSUE THREAD

**Issue by H-adorable** [naturomics/CapsNet-Tensorflow#39]
When run in windows + GTX960M，I get this error
```
InternalError (see above for traceback): Dst tensor is not initialized.
```
Some blogs told that it is caused by lack of GPU memory. But I cannot fix the problem. Wish some one could help me.

运行在Windows10 + GTX960M，出现错误
```
InternalError (see above for traceback): Dst tensor is not initialized.
```
我查了些博客，说是GPU 内存不足的时候，会出现这个错误。希望能够修复这个问题。

**Comment by naturomics** [comment]
Please read the `README` carefully, the default parameter `batch_size` is set to `128`. Your GPU memory is too small for this setting, change it, eg. `python main.py  --batch_size 32` or  a smaller `batch_size`
