### ISSUE TITLE
will the norm in squash func be a scalar

### ISSUE THREAD

**Issue by vpegasus** [naturomics/CapsNet-Tensorflow#40]
Hi, good job !
I have a small question that: in the squash func, you keep the dims of norm('vec_squared_norm') as 
 that of the  'vector',  I wonder why not collapse its dims to [batch_size,1] ?
From where I stand, the norm should be a scalar.
e.g.:
 x= [a,b,c,d] 
||x||^2 = norm(x)^2 = (|a|^2+|b|^2+|c|^2+|d|^2)

thus  x --> norm(x)^2 :  [batch_size, 1, num_caps, vec_len, 1] --> [batch_size, 1] ?

**Comment by naturomics** [comment]
Just for the convenience of computing
