### ISSUE TITLE
Deer man

### ISSUE THREAD

**Issue by nb312** [naturomics/CapsNet-Tensorflow#5]
I think we should make a wechat group here for who interest this kind of subject. My wechat is bn31201 . Hope your adding, make some deep communicating.

**Comment by naturomics** [comment]
@nb312 It's a good idea. I've sent you an add request

**Comment by bingo619** [comment]
Please post the Wechat group QR code here.

**Comment by nb312** [comment]
The group QR always past due.please add my wechat "bn31201". I will pull you into our group which naturomics is in.

**Comment by nb312** [comment]
@bingo619

**Comment by naturomics** [comment]
Here is my weChat QR, if the Wechat group QR in the REAM is invalid, you can add me.
![my_wechat_qr](https://user-images.githubusercontent.com/19428529/32166338-796b29dc-bda0-11e7-86b9-a2202fc3b10f.png)

**Comment by bingo619** [comment]
Thanks guys, already in the group.

**Comment by 0x454447415244** [comment]
Group is full, how can I join?

**Comment by soldier828** [comment]
I have added your WeChat, message "Capsule". @ nb312

**Comment by soldier828** [comment]
I have added your WeChat, message "Capsule". @nb312
