### ISSUE TITLE
Cannot evaluate the model when using python main --is_training=False

### ISSUE THREAD

**Issue by kumarlamichhane** [naturomics/CapsNet-Tensorflow#52]
Evaluating/Testing the trained model using `python main.py --is_training=False` gives the following error
**ValueError: Can't load save_path when it is None.**

**Comment by naturomics** [comment]
Can you describe it in more detail? I don't use any variable `save_path` in my code. Did you modify something else? Evaluation/Testing function is OK in my computer.

**Comment by Allong12** [comment]
Have you already run training on the MNIST dataset or downloaded a pre-trained model?

If you run `python main.py`, it will begin training and save a model every `cfg.save_freq` epochs (by default 3 as per config.py) and save it into `cfg.logdir` 

A complete logdir folder should contain a file named `checkpoint` and multiple `model_epoch_###_step_##` files such as those found in [naturomics' Baid repo ](https://pan.baidu.com/s/1pLp8fdL#list/path=%2FSharing%2FCapsNet-saved-model%20and%20materials%2Fmnist%2Flog_4_iter&parentPath=%2FSharing) ( for which the password can be found on the front github README page, just below the results)

If those files are not in there, you would get an error similar to the one you described.

**Comment by kumarlamichhane** [comment]
I trained my model and it returned me all the losses, val_acc, train_acc.. 
but then when i run the test by using `python main.py --is_training=False` or change the is_training to false in config file.... i will get an error

**Comment by kumarlamichhane** [comment]
Apologies.. for disturbing u good people..
The error was due to not saving the models when required.
the error was due to running the training for 1 epoch and saving the models after 3 epochs.

```
cfg.save_freq=3 and
cfg.epoch=1 gave me the error
```
doing 
```
cfg.save_freq=3 and
cfg.epoch=1
```
solved the problem

I really appreciate your help.
